name: List of Non standard profiles

on:
  workflow_dispatch:
    inputs:
      action_branch:
        description: The branch of the action to use
        default: main
        
      organization:
        description: The organization to process
        default: internal-test-organization
        
jobs:
  orgs:
    name: Analyze Organization
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.action_branch }}
        
      - name: Analyze organization
        id: analyze_org
        uses: ./
        with:
          token: ${{ secrets.OCTODEMO_TEMP_TOKEN }}
          organization: ${{ github.event.inputs.organization }}
          
      - name: Results
        run: |
          
          echo "Non- standard User - ${{ steps.analyze_org.outputs.jsonfinallist }}"
          echo "Non Standard UserCount - ${{ steps.analyze_org.outputs.usercount }}"

      - name: Attach Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            ${{ steps.analyze_org.outputs.jsonfinallist.json }}

# Job for sending mails-


  send_mail : 
    runs-on : Ubuntu-latest
    
    steps:
      - name: Send mail
        uses: ./
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Test Email trigger by github actions
          # Required recipients' addresses:
          to: suripa.saha110@gmail.com
          # Required sender full name (address can be skipped):
          from: Suripa
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Hi ! Email has been triggered successfully,
          # Optional carbon copy recipients:
          cc: pradipta.chatterjee98@gmail.com
          # Optional blind carbon copy recipients:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          

        
